apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
  labels:
    app: realms-monitoring-service-mainnet-prod
  name: realms-monitoring-service-mainnet-prod
  namespace: default
  resourceVersion: "65918483"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: realms-monitoring-service-mainnet-prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: realms-monitoring-service-mainnet-prod
    spec:
      containers:
      - env:
        - name: NETWORK_NAME
          value: "mainnet"
        - name: NX_ENVIRONMENT
          value: "mainnet_prod"
        - name: RPC_URL
          valueFrom:
            secretKeyRef:
              key: MAINNET_RPC_URL
              name: env-vars
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: SQUADS_MESSAGING_PRIVATE_KEY_MAINNET_PROD
              name: env-vars
        image: dialectlab/realms-monitoring-service:0.1.0
        imagePullPolicy: Always
        name: realms-monitoring-service-mainnet-prod
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
